### ISSUE TITLE
nix path-info output schema has changed, causing instantiate.sh to fail on certain architectures

### ISSUE THREAD

**Issue by dnaq** [Gabriella439/terraform-nixos-ng#8]
The old output schema seemed to be an array, which matches what instantiate.sh assumes in its `jq` invokation. However with newer nix versions the schema seems to have changed to an object of paths instead...

e.g. using nix 2.18.1
```
[
  {
    "path": "/nix/foo",
    ...
  }
]
```

using nix 2.19.2
```
{
  "/nix/foo": {
    ...
  }
}
```

causing the `jq` invokation to fail.

This can be solved for some versions by changing the jq invokation to `jq '{ "path": keys[] }` instead, but then it will fail for the older output format.

One hack could be to try the first jq invocation, and fall back to the second one on failure. But maybe a better option would be to change to something with a stable output format.

I can make a pull request with the hacky option if needed.

**Comment by dnaq** [comment]
Another option might be to skip the --json parts completely, and just use the output from `nix path-info`, since that is the store path we are after.

**Comment by Gabriella439** [comment]
Yeah, I'd be fine with either option, but it sounds like using the non-`--json` approach might be the way to go.  The only reason I used `--json` is because I thought it would make things more robust but I guess not 🤷🏻‍♀️
